MONGODB_HOST: mongodb-{{ env }}.vicky08.fun
REDIS_HOST: redis-{{ env }}.vicky08.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.vicky08.fun
MYSQL_HOST: mysql-{{ env }}.vicky08.fun

CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.vicky08.fun
CART_HOST: cart.backend-alb-{{ env }}.vicky08.fun
USER_HOST: user.backend-alb-{{ env }}.vicky08.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.vicky08.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.vicky08.fun