- name: app-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: java-setup
  ansible.builtin.include_role:
    name: common
    tasks_from: java.yaml

- name: installing python and mysql libraries
  ansible.builtin.pip:
    executable: pip3.9
    name: "{{ item }}"
  loop:
  - cryptography
  - PyMySQL

- name: importing shipping data to mysql
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"   #<mysql ipaddress>
    login_user: "{{ MYSQL_ROOT_USER }}"
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql  
 

- name: system-setup
  ansible.builtin.include_role:
    name: common
    tasks_from: system-setup.yaml
  
  


  
  


  

