
  - name: disable nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: creating html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory

  - name: downloading frontend content
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: extracting frontend content
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html/
      remote_src: yes

  - name: delete default nginx.conf
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy nginx.conf
    ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf 
    notify: restart nginx

  

  
